### ISSUE TITLE
Setup automated tests in CI

### ISSUE THREAD

**Issue by Surendrajat** [APKLab/APKLab#64]
To do:
- [x] OS: Linux #61 
- [x] OS: Windows #63 
- [x] OS: macOS #63 
- [x] Download and Install dependencies (ApkTool, Jadx, Uber-apk-signer) #61
- [x] Decode APK with ApkTool #61
- [x] Decompile APK with Jadx #61
- [x] Rebuild APK with ApkTool #61
- [x] Clean Resource Framework Dir #74
- [x] Malware Analysis report generation test with Quark-Engine #92
- [x] Apply MITM Patch #158 
- [x] git repo initialization in project dir #158 
- [ ] Verify Signature on Rebuild (builtin and user-provided Keystore)
- [ ] Install Resource Framework APK (NYI)
